### ISSUE TITLE
需过滤结果字词

### ISSUE THREAD

**Issue by lisposter** [BoogeeDoo/hua#1]
- 单字结果
  ![image](https://cloud.githubusercontent.com/assets/741001/13519268/e80f2662-e210-11e5-9acf-f320ae44d450.png)
- 标点
  ![image](https://cloud.githubusercontent.com/assets/741001/13519299/53269278-e211-11e5-87a7-db4d24b98b66.png)

**Comment by XadillaX** [comment]
好的。
